# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Julia  # Name of the book
author: The Molecular Sciences Software Institute
copyright: "2025"

execute:
  execute_notebooks: force
  allow_errors: true

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/MolSSI-Education/julia-introduction
  path_to_book: book/
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-FHKVGE8HKZ
  extra_css:
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css
    - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css


sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme_options: 
      logo:
        image_light: images/molssi_main_logo.png
        image_dark: images/molssi_main_logo_inverted_white.png
    nb_merge_streams: true
