name: Build and Deploy Book

on:
  push:
    branches:
      - main

permissions: write-all

env:
  PYTHON_VERSION: 3.12
  JULIA_VERSION: 1.11
  KERNEL_NAME: "julia_kernel"

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Set up Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ env.JULIA_VERSION }}
          project : '.' # this is the default

      - name: Build Books
        run : | 
          make html

      # Deploy to GitHub Pages
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book/_build/html
