name: Build and Deploy Book

on:
  push:
    branches:
      - ethan-test

permissions: write-all

env:
  PYTHON_VERSION: 3.12
  JULIA_VERSION: 1.11
  KERNEL_NAME: "julia_kernel"

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Set up Julia
      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ env.JULIA_VERSION }}
          project : '.' # this is the default

      # Install Julia kernel
      # kernel will be named KERNEL_NAME-JULIA_VERSION
      # JULIA_VERSION is appened by IJulia automatically
      - name: Setup IJulia 
        run: |
          julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia"); using IJulia; installkernel("${{ env.KERNEL_NAME }}")'

      # Manually set kernel in notebooks
      - name: Run script file
        run: |
          chmod +x patch_kernel_versions.sh
          sh scripts/patch_kernel_versions.sh "${{ env.JULIA_VERSION }}" "julia_kernel-${{ env.JULIA_VERSION }}"
        shell: bash

      - name: Setup Julia Environment 
        run: |
          julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
      
      # Build the book
      - name: Build the book
        run: |
          julia -e 'using Pkg; Pkg.activate(".")'
          jupyter-book build book --all

      # Deploy to GitHub Pages
      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book/_build/html
